# Generated by Django 5.1.4 on 2025-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='health',
            name='destinations',
        ),
        migrations.AddField(
            model_name='health',
            name='g_maps',
            field=models.URLField(blank=True, help_text='Google Maps URL', max_length=2000),
        ),
        migrations.AddField(
            model_name='health',
            name='guides',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='health',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='health',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
