# Generated by Django 5.1.4 on 2025-01-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_health_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='close_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='health',
            name='open_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FasilitasHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasilitas', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas', to='health.health')),
            ],
        ),
    ]
