# Generated by Django 5.1.4 on 2025-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_health_close_hours_alter_health_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehealth',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
