# Generated by Django 5.1.4 on 2025-01-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_imagehealth_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehealth',
            name='title',
        ),
        migrations.AlterField(
            model_name='health',
            name='title',
            field=models.CharField(help_text='Dont more than 255 characters', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagehealth',
            name='image',
            field=models.ImageField(help_text='Image size max 10MB and max resolution 2000x2000px auto compress', upload_to='health/'),
        ),
    ]
