# Generated by Django 5.1.4 on 2025-02-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_alter_artikel_meta_keyword_alter_artikel_meta_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='meta_keyword',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='meta_tag',
        ),
        migrations.AddField(
            model_name='artikel',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'NoIndex, Follow'), ('noindex, nofollow', 'NoIndex, NoFollow')], default='index, follow', help_text='Kontrol indexing halaman (robots meta tag)', max_length=50),
        ),
        migrations.AddField(
            model_name='artikel',
            name='meta_title',
            field=models.CharField(default=0, help_text='Judul untuk SEO (meta title)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artikel',
            name='meta_description',
            field=models.TextField(default=0, help_text='Deskripsi untuk SEO (meta description)'),
            preserve_default=False,
        ),
    ]
