# Generated by Django 5.1.4 on 2025-02-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_remove_artikel_meta_keyword_remove_artikel_meta_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='kategoriartikel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
