# Generated by Django 5.1.4 on 2025-02-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_alter_artikel_slug_alter_kategoriartikel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Deskripsi alternatif untuk gambar (SEO & aksesibilitas)', max_length=255),
        ),
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artikel_images/'),
        ),
    ]
