# Generated by Django 5.1.4 on 2025-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='location',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
