# Generated by Django 5.1.4 on 2025-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinations_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='description_2',
        ),
        migrations.AddField(
            model_name='destinations',
            name='g_maps',
            field=models.URLField(blank=True, help_text='Google Maps URL', max_length=2000),
        ),
        migrations.AddField(
            model_name='destinations',
            name='guides',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
