# Generated by Django 5.1.4 on 2025-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destinations_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='close_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destinations',
            name='open_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
