# Generated by Django 5.1.4 on 2025-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_destinations_close_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='close_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='description',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
