# Generated by Django 5.1.4 on 2025-01-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fauna',
            name='description_2',
        ),
    ]
