# Generated by Django 5.1.4 on 2025-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aianalytics_chatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalytics',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalytics',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalytics',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aianalytics',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
