# Generated by Django 5.1.4 on 2025-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aianalytics_request_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedbackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, '👎 Tidak Membantu'), (2, '👍 Membantu')])),
                ('has_comment', models.BooleanField(default=False)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Feedback Analytics',
                'verbose_name_plural': 'AI Feedback Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
