# Generated by Django 5.1.4 on 2024-12-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('db_query_time', models.FloatField(help_text='Database query time in milliseconds', null=True)),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB', null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('content_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='analytics_r_timesta_d80d79_idx'), models.Index(fields=['endpoint'], name='analytics_r_endpoin_f480f5_idx'), models.Index(fields=['content_type'], name='analytics_r_content_de4e4a_idx')],
            },
        ),
    ]
