# Generated by Django 5.1.4 on 2024-12-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_requestlog_error_message_requestlog_error_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_throttled',
            field=models.BooleanField(default=False, help_text='Whether request was throttled'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='rate_limit_count',
            field=models.IntegerField(default=0, help_text='Number of requests within time window'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='rate_limit_key',
            field=models.CharField(blank=True, help_text='Key used for rate limiting (IP or API key)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='rate_limit_window',
            field=models.DateTimeField(blank=True, help_text='Start of the rate limit window', null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['rate_limit_key'], name='analytics_r_rate_li_27bdc1_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['rate_limit_window'], name='analytics_r_rate_li_060457_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_throttled'], name='analytics_r_is_thro_2dda85_idx'),
        ),
    ]
