# Generated by Django 5.1.4 on 2024-12-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_requestlog_is_throttled_requestlog_rate_limit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key used for request', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='auth_method',
            field=models.CharField(blank=True, help_text='Method of authentication used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='auth_status',
            field=models.CharField(blank=True, help_text='Authentication status (success/failed)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Flag for suspicious activity'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='security_flags',
            field=models.JSONField(blank=True, help_text='Additional security flags and details', null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='ID of authenticated user', null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['auth_status'], name='analytics_r_auth_st_1be12f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user_id'], name='analytics_r_user_id_c0c46f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_suspicious'], name='analytics_r_is_susp_354294_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['auth_method'], name='analytics_r_auth_me_2aafa4_idx'),
        ),
    ]
