# Generated by Django 5.1.4 on 2024-12-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_requestlog_conversion_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the custom event', max_length=100)),
                ('event_category', models.CharField(help_text='Category of the event', max_length=50)),
                ('event_value', models.JSONField(blank=True, help_text='Custom event data/payload', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_event', models.CharField(blank=True, help_text='Previous event in user journey', max_length=100, null=True)),
                ('next_event', models.CharField(blank=True, help_text='Next event in user journey', max_length=100, null=True)),
                ('journey_step', models.IntegerField(default=1, help_text='Step number in the user journey')),
                ('source', models.CharField(blank=True, help_text='Source of the event', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event metadata', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_name'], name='analytics_c_event_n_b80704_idx'), models.Index(fields=['event_category'], name='analytics_c_event_c_18c0cc_idx'), models.Index(fields=['timestamp'], name='analytics_c_timesta_94da58_idx'), models.Index(fields=['session_id'], name='analytics_c_session_3d4e7d_idx'), models.Index(fields=['user_id'], name='analytics_c_user_id_17c8cc_idx'), models.Index(fields=['journey_step'], name='analytics_c_journey_089765_idx')],
            },
        ),
    ]
