# Generated by Django 5.1.4 on 2024-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_customevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('action_type', models.CharField(help_text='Type of action (access/export/delete)', max_length=50)),
                ('data_category', models.CharField(help_text='Category of data accessed', max_length=50)),
                ('data_description', models.TextField(help_text='Description of accessed data')),
                ('affected_users', models.JSONField(blank=True, help_text='List of affected user IDs', null=True)),
                ('legal_basis', models.CharField(help_text='Legal basis for processing', max_length=50)),
                ('consent_reference', models.CharField(blank=True, help_text='Reference to user consent', max_length=100, null=True)),
                ('data_retention', models.DateTimeField(help_text='When this data should be deleted')),
                ('sensitivity_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='low', max_length=20)),
                ('request_id', models.CharField(help_text='Unique request identifier', max_length=100)),
                ('source_system', models.CharField(help_text='System initiating the request', max_length=50)),
                ('authorized_by', models.CharField(blank=True, help_text='Person who authorized access', max_length=100, null=True)),
                ('purpose', models.TextField(help_text='Purpose of data access')),
                ('processing_location', models.CharField(help_text='Location where data is processed', max_length=100)),
                ('cross_border', models.BooleanField(default=False, help_text='Whether data crosses borders')),
                ('third_parties', models.JSONField(blank=True, help_text='Third parties data is shared with', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional compliance metadata', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='analytics_c_timesta_217819_idx'), models.Index(fields=['action_type'], name='analytics_c_action__9301b0_idx'), models.Index(fields=['data_category'], name='analytics_c_data_ca_fe4886_idx'), models.Index(fields=['sensitivity_level'], name='analytics_c_sensiti_5ab3c3_idx'), models.Index(fields=['request_id'], name='analytics_c_request_420f23_idx'), models.Index(fields=['user_id'], name='analytics_c_user_id_304ffa_idx')],
            },
        ),
    ]
