# Generated by Django 5.1.4 on 2025-01-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliner', '0002_remove_kuliner_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuliner',
            name='close_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kuliner',
            name='open_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kuliner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ListMenuKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_menu', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kuliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_menu', to='kuliner.kuliner')),
            ],
        ),
    ]
