# Generated by Django 5.1.4 on 2025-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuliner', '0004_alter_kuliner_close_hours_alter_kuliner_open_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuliner',
            name='close_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kuliner',
            name='open_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
