# Generated by Django 5.1.4 on 2025-02-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_slug', models.SlugField(unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], max_length=50)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_size', models.PositiveIntegerField(help_text='Size in square meters')),
                ('room_capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('allow_pets', models.BooleanField(default=False)),
                ('provide_breakfast', models.BooleanField(default=False)),
                ('featured_room', models.BooleanField(default=False)),
                ('room_description', models.TextField()),
                ('extra_facilities', models.TextField(blank=True, null=True)),
                ('room_status', models.BooleanField(default=True, help_text='Available or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hotel', models.ImageField(upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_room', models.ImageField(upload_to='room_images/')),
                ('detail_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.detailroom')),
            ],
        ),
    ]
