# Generated by Django 5.1.4 on 2025-02-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailroom',
            name='featured_room',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailroom',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
