# Generated by Django 5.1.4 on 2025-02-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailroom',
            name='meta_description',
            field=models.TextField(default=0, help_text='Deskripsi untuk SEO (meta description)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailroom',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'NoIndex, Follow'), ('noindex, nofollow', 'NoIndex, NoFollow')], default='index, follow', help_text='Kontrol indexing halaman (robots meta tag)', max_length=50),
        ),
        migrations.AddField(
            model_name='detailroom',
            name='meta_title',
            field=models.CharField(default=0, help_text='Judul untuk SEO (meta title)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_description',
            field=models.TextField(default=0, help_text='Deskripsi untuk SEO (meta description)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'NoIndex, Follow'), ('noindex, nofollow', 'NoIndex, NoFollow')], default='index, follow', help_text='Kontrol indexing halaman (robots meta tag)', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_title',
            field=models.CharField(default=0, help_text='Judul untuk SEO (meta title)', max_length=255),
            preserve_default=False,
        ),
    ]
