# Generated by Django 5.1.4 on 2025-02-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_detailroom_meta_description_detailroom_meta_robots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehotel',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Deskripsi alternatif untuk gambar hotel (SEO & aksesibilitas)', max_length=255),
        ),
        migrations.AddField(
            model_name='imageroom',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Deskripsi alternatif untuk gambar kamar (SEO & aksesibilitas)', max_length=255),
        ),
    ]
