# Generated by Django 5.1.4 on 2025-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_alter_flora_title_alter_imageflora_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='meta_description',
            field=models.TextField(default=0, help_text='Description for SEO (meta description)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flora',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'NoIndex, Follow'), ('noindex, nofollow', 'NoIndex, NoFollow')], default='index, follow', help_text='Control indexing of this page (robots meta tag)', max_length=50),
        ),
        migrations.AddField(
            model_name='flora',
            name='meta_title',
            field=models.CharField(default=0, help_text='Title for SEO (meta title)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageflora',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image (SEO & accessibility)', max_length=255),
        ),
    ]
